---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r cars}
dna_2015 <- readRDS("~/git/business_innovation/data/working/DNA_Aggregated/dna_2015.RDS")
colnames(dna_2015)
dna_2015_hl = dna_2015 %>% select(an, title)
dna_2015_body = dna_2015 %>% select(an, body)
test <- head(dna_2015_body)
test <- test %>% mutate(length = nchar(body), tokens = stringr::str_split(gsub('[[:punct:]]+', ' ', body), " ", simplify = FALSE))

test <- tidyr::unnest(test[,c(1, 3,4)])

test <- test %>% filter(!dataplumbr::var.is_blank(tokens))

test <- test %>% mutate(tokens = str_replace_all(tokens, "\\n", " "))

nrow(dna_2015_body)

```



```{r}
words <-
      unlist(stringr::str_split(gsub('[[:punct:] ]+', ' ', paragraphs[innov_text]), " ", simplify = FALSE))
words <- words %>%
      str_replace(pattern = "\u0092", "") %>%
      str_replace(pattern = "\u0093", "") %>%
      str_replace(pattern = "\u0094", "") %>%
      str_replace(pattern = "\u0095", "") %>%
      str_replace(pattern = "\u0097", "") %>%
      str_replace(pattern = "\u0099", "")
eng <- hunspell_check(words, dict = dictionary("en_US"))
caps <- grepl("^[[:upper:]]", words)
```



```{r}

dna_2015_hl

if (exists("fin_o") == TRUE) rm(fin_o)

for (i in dna_2015_hl[1]) { 
  char_ct <- nchar(dna_2015_hl$title[i])
  if(char_ct < 5,
     words[i] <- unlist(stringr::str_split(gsub('[[:punct:] ]+', ' ', dna_2015_hl$title[i]), " ", simplify = FALSE))
           
          , return(NA))
}

words
#dna_2015_hl$wc[i] <- l

    
    words <- words %>%
      str_replace(pattern = "\u0092", "") %>%
      str_replace(pattern = "\u0093", "") %>%
      str_replace(pattern = "\u0094", "") %>%
      str_replace(pattern = "\u0095", "") %>%
      str_replace(pattern = "\u0097", "") %>%
      str_replace(pattern = "\u0099", "")
    eng <- hunspell_check(words, dict = dictionary("en_US"))
    caps <- grepl("^[[:upper:]]", words)

    output1 <- tibble::tibble(
      "Company" = company,
      "Month" = month,
      "Year" = year,
      "Words" = words,
      "English" = eng,
      "Capitals" = caps
    )
    # output2 <- output1 %>%
    #   filter(English == FALSE & Capitals == TRUE & nchar(Words)>3 & substrRight(Words, 1) != "s") %>%
    #   group_by(Words) %>%
    #   summarise(count = n()) %>%
    #   arrange(desc(count)) %>%
    #   data.table::as.data.table()

    #print(output1)

    # Group by Company and Words and get count of records for each group. Then order by count descending.
    o1 <- setDT(output1)
    o2 <-
      o1[English == FALSE & Capitals == TRUE & nchar(Words) > 3 & substrRight(Words, 1) != "s",
         .(count = .N),
         .(Company, Year, Words)][order(-count)]
    write_csv(o1, path = paste0("~/git/business_innovation/data/business_innovation/working/sec/secwordlists/", str_extract(str_extract(i, "(?<=Edgar_filings_folders/)(.*)(?=.txt)"), "(?<=/)(.*)") , ".csv"))

    #print(o2)

    # combine results with final data.table
    if (exists("fin_o") == FALSE)
      fin_o <- o2
    else
      fin_o <- rbindlist(list(fin_o, o2))
  })
}
```



