
#library(rvest)


# Extract 
focalURL = "https://www.sec.gov/Archives/"

getFilings <- function(startYear, endYear, filingType){
  # Set generic URL start point, build header to allow requests to go through without 403 errors
  focalURL = "https://www.sec.gov/Archives/"
  headerVector = vector()
  headerVector["User-Agent:"] = "Q Student quinc012@umn.edu"
  headerVector["Accept-Encoding:"] = "gzip, deflate"
  headerVector["Host:"] = "www.sec.gov"
  
  for (year in startYear:endYear) {
    for (qtr in c("QTR1","QTR2","QTR3","QTR4")) {
      # Build target URL
      targetFile = paste0(focalURL,"edgar/full-index/",year,"/",qtr,"/master.gz")
      print(targetFile)
      
      # Temporarily download the .gz file so it can be uncompressed by the gzfile function
      tempFileName = paste0(year,qtr,".gz")
      download.file(targetFile, tempFileName, headers = headerVector)
      qtrData = read.delim(gzfile(tempFileName), col.names = c("CIK","CompanyName","FormType","DateFiled","Filename"), sep="|")
      unlink(tempFileName)  # Delete file to avoid directory clutter
      
      # Identify the row with header info, then delete it and all previous rows
      headerRow = which(qtrData$CIK=="CIK")[1]
      qtrData = qtrData[-c(1:headerRow),]
      
      # Filter out all but the targeted Filing Type
      qtrData = qtrData[qtrData$FormType=="10-K",]
      print(nrow(qtrData))
      qtrData["FilingYear"] = year
      
      # Store in collection dataframe
      if ((year==startYear)&(qtr=="QTR1")) {
        allData = qtrData
      } 
      else {
        allData = rbind(allData,qtrData)
      }
    }
  }
  return(allData)
}

testData = getFilings(2016,2021)
write.csv(testData,"SEC10KList.csv", row.names = FALSE)


library(R.utils)  # only needed if using the gunzip function


# Wrapper to download documents, with error catching so the long process doesn't fail completely
downloadEdgarTxt <- function(edgarFilename, destinationFilename) {
  out = tryCatch({
    headerVector = vector()
    headerVector["User-Agent:"] = "Q Student quinc012@umn.edu"
    headerVector["Accept-Encoding:"] = "gzip, text"
    headerVector["Host:"] = "www.sec.gov"
    fullUrl = paste0("https://www.sec.gov/Archives/",edgarFilename)
    download.file(fullUrl, destinationFilename, headers = headerVector, mode = "wb")  # mode needs to explicitly be "wb" on Windows to download as a gzip file because reasons
    TRUE
  },
  error = function(cond){
    message("Error downloading TXT.  Original error message:")
    message(cond)
    return(FALSE)
  },
  warning = function(cond){
    message("Warning downloading TXT.  Original warning message:")
    message(cond)
    return(FALSE)
  }
  )
  return(out)
}

downloadEdgarTxt("edgar/data/1000230/0001437749-16-024214.txt", "test6.txt.gzip")
gunzip("test6.txt.gzip", "test6.txt")


# Function to download all txt documents, guided by a csv full of targets generated by the getFilings function
downloadAllEdgarTxts <- function(csvOfTargets) {
  # Initialize a timing variable to ensure we don't try to download more than 10 per second
  timeList = rep(0,10)
  startTime = as.numeric(proc.time()['elapsed'])
  
  # Pull in the dataframe of target files to loop over, add column to track progress
  dfOfTargets = read.csv(csvOfTargets)
  dfOfTargets$Downloaded = FALSE
  totalTargets = nrow(dfOfTargets)
  for (i in 1:totalTargets){
    # Compare current time to the time 10 requests ago to make sure at least a second has passed
    activeIndex = ((i-1)%%10)+1  # Avoid zero indexes
    currTime = as.numeric(proc.time()['elapsed'])
    timeDiff = currTime-timeList[activeIndex]
    timeList[activeIndex] = currTime  # Replace time from 10 requests ago
    if (timeDiff<1) {
      Sys.sleep(1-timeDiff)
      timeList[activeIndex] = currTime+(1-timeDiff)  # Store a more accurate request time based on the delay
    }
    
    # Download file
    targetFilename = dfOfTargets$Filename[i]
    localFilename = paste0(dfOfTargets$CIK[i],"-",dfOfTargets$FilingYear[i],"-",dfOfTargets$CompanyName[i],".txt")
    localFilename = gsub("/|\\\\","",localFilename)  # Remove slashes, which sometimes show up in the CompanyName column
    downloadSuccessful = downloadEdgarTxt(targetFilename, localFilename)  # Returns TRUE if download was successful, FALSE otherwise
    dfOfTargets$Downloaded[i] = downloadSuccessful
    
    # Periodically save a list of remaining targets to store progress in case of catastropic errors
    if ((i%%250)==0) write.csv(dfOfTargets[dfOfTargets$Downloaded==FALSE,], paste0("remaining-",csvOfTargets), row.names = FALSE)
    
    # Indicate overall progress
    if ((i%%5)==0) print(paste0(round(100*i/totalTargets),"% complete - ",i," of ",totalTargets," in ",(currTime-startTime)," seconds"))
    
    # Early break for testing
    #if (i==6) break
  }
}
downloadAllEdgarTxts("SEC10KList.csv")




headerVector = vector()
headerVector["User-Agent:"] = "Q Student quinc012@umn.edu"
headerVector["Accept-Encoding:"] = "text"
headerVector["Host:"] = "www.sec.gov"

testFileUrl = "https://www.sec.gov/Archives/edgar/data/1122304/0001193125-15-118890.txt"
testFileUrl = "https://www.sec.gov/Archives/edgar/data/1000209/0001193125-16-495428.txt"
download.file(testFileUrl, "testFileDownload.txt", headers = headerVector)


## Unimortant troubleshooting stuff

gunzip("testFileDownload.txt.gz", remove = FALSE)
gzConnection = gzfile("testFileDownload.gz", encoding = "UTF-8-BOM")
testDoc = read_file(gzConnection)

html = read_html(testFileUrl)









# testData = read.delim("C:/Users/Ferre/Documents/Random/master.idx", skip=9, sep="|")
# testData = read.delim(target, col.names = c("CIK","CompanyName","FormType","DateFiled","Filename"), sep="|")
# headerVector = vector()
# headerVector["User-Agent:"] = "Q Student quinc012@umn.edu"
# headerVector["Accept-Encoding:"] = "gzip, deflate"
# headerVector["Host:"] = "www.sec.gov"
# 
# con = url("https://www.sec.gov/Archives/edgar/full-index/2016/QTR1/master.gz", headers = headerVector)
# testData = read.delim(con, col.names = c("CIK","CompanyName","FormType","DateFiled","Filename"), sep="|")
# testGz = gzfile("master.gz")
# 
# testFileName = "2016Q1Master.gz"
# download.file("https://www.sec.gov/Archives/edgar/full-index/2016/QTR1/master.gz", testFileName, headers = headerVector)
# testData = read.delim(gzfile(testFileName), col.names = c("CIK","CompanyName","FormType","DateFiled","Filename"), sep="|")

